const assert=require('assert'),C=require('../climate/model.js'),M=require('../global/merged-model.js');
const s=C.parse('#/region/IND/IND:IN.ADM2.00008?crop=rice&layer=precipitation&statistic=p95&metric=enso&model=quadratic&amplitude=3&index=mei&common=1&mode=advanced');
assert.deepEqual(C.parse(C.url(s)),s);
const fit={x_min:-2,x_max:2,models:{quadratic:{coef:[4,.2,-.4,.1],cov:[[.04,.003],[.003,.002]],neutral:4,cv:[.1,.2]}}};
const r=C.estimate(fit,'quadratic',3);
assert(Math.abs(r.value-(-.3))<1e-12,'Native rainfall contrast, no exponential transform');
assert(Math.abs(r.se**2-(9*.04+54*.003+81*.002))<1e-12,'Response covariance includes the cross term');
assert(r.extrapolated&&r.validated);
assert.equal(C.estimate(fit,'quadratic',0).value,0);
const badFit={n:40,x_min:-2,x_max:2,models:{linear:{coef:[.2,0,-1],cov:[[.01]],neutral:.2,cv:[.1,.2]}}};
const rejected=C.attach([{sid:'x',enough:true}],{...s,model:'linear',period:'1981-2024',exposure:'season',scale:'native',amplitude:1},{x:{'1981-2024':badFit}},null,{units:'°C'})[0];
assert.equal(rejected.value,null);assert(!rejected.enough);assert(rejected.status.includes('negative rainfall'));
const rows=[{enough:true,mapped:true,value:-3},{enough:true,mapped:true,value:0},{enough:true,mapped:true,value:3},{enough:false,mapped:true,value:99}];
const d=C.domain(rows,s);assert.deepEqual(d,{lo:-3,hi:3,diverging:true});assert.equal(C.color(null,d),'#dce1dd');assert.notEqual(C.color(0,d),C.color(null,d));
const wx=[[1981,-3,1,0,null,90,90,90,90],[1982,null,null,null,null,89,89,89,90],[2025,9,10,4,8,90,90,90,90]];
assert.deepEqual(C.observations(wx,{...s,layer:'temperature',statistic:'mean',period:'1981-2024'}),[[1981,-3]]);
assert.deepEqual(C.observations(wx,{...s,statistic:'mean',period:'1981-2024'}),[[1981,0]]);
const scale=M.comparisonScale([[2000,2],[2001,4],[2002,6]],[[2000,-1],[2001,0],[2002,1]]);
assert(Math.abs(scale.project(1)-scale.project(0)-2)<1e-10);
console.log('PASS climate route, native contrasts, covariance, zero versus missing, signed temperatures, shared color scale, ENSO axis scaling');
