const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {parseHTML}=require('linkedom'),ROOT=path.join(__dirname,'../climate');
const {window}=parseHTML(fs.readFileSync(path.join(ROOT,'index.html'),'utf8')),document=window.document;
window.HTMLElement.prototype.focus=()=>{};
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._value??(this.querySelector('option[selected]')||this.querySelector('option'))?.value??''},set(v){this._value=String(v)},configurable:true});
const location={hash:'#/country/IND?crop=wheat',href:'https://example.org/climate/'},requests=[];
const context=vm.createContext({document,window,location,history:{replaceState(a,b,h){location.hash=h},pushState(a,b,h){location.hash=h}},navigator:{clipboard:{writeText:async()=>{}}},maplibregl:{Map:function(){throw Error('No WebGL test')}},URL,URLSearchParams,Blob,Response,DecompressionStream,TextDecoder,setTimeout,console,fetch:async p=>{requests.push(p);try{return new Response(fs.readFileSync(path.join(ROOT,p)),{status:200})}catch{return new Response('',{status:404})}}});
context.AtlasModel=require('../global/merged-model.js');context.ClimateModel=require('../climate/model.js');const run=s=>vm.runInContext(s,context);
run(fs.readFileSync(path.join(ROOT,'app.js'),'utf8'));
(async()=>{
 for(let i=0;i<300&&!document.querySelector('#locations button');i++)await new Promise(r=>setTimeout(r,50));
 assert(document.querySelector('#locations button'),document.querySelector('#status').textContent);
 const route=async hash=>{location.hash=hash;await run('render()');assert(!document.querySelector('#status').classList.contains('error'),document.querySelector('#status').textContent)};
 assert(!requests.some(p=>p.includes('/observations/')),'Observations load only when a panel opens');
 const r=run('selected.find(r=>r.country==="IND"&&r.enough)'),base=`#/region/IND/${encodeURIComponent(r.id)}?crop=wheat`;
 await route(base);
 assert(document.querySelector('#detail svg'));
 assert.equal(run('detailData.record.sid'),r.sid);
 assert(document.querySelector('#detail').textContent.includes('Both charts share the same year axis'));
 const charts=[...document.querySelectorAll('.chart-box svg')];
 const years=svg=>[...svg.querySelectorAll('text')].map(t=>t.textContent).filter(t=>/^\d{4}$/.test(t));
 assert.deepEqual(years(charts[0]),years(charts[1]),'Weather and yield have aligned year axes');
 await route(base+'&common=1');assert(document.querySelector('#common-years').hasAttribute('checked'));
 const years2=[...document.querySelectorAll('.chart-box svg')].map(years);assert.deepEqual(years2[0],years2[1]);
 await route(base+'&metric=enso&index=mei&model=quadratic');
 assert(run('detailData.record.response'),'Native weather response available');
 assert(document.querySelectorAll('.fitted-observation').length>=20);
 assert(!document.querySelector('#detail').innerHTML.includes('undefined'));
 assert(!document.querySelector('#detail').innerHTML.includes('NaN'));
 assert(document.querySelector('#detail').textContent.includes('not a forecast'));
 const response=run('detailData.record.response.value'),color=run('C.color(detailData.record.value,scale)');
 assert.equal(response,run('selected.find(r=>r.id===state.unit).value'));
 run('map={getSource:()=>({setData:x=>{globalThis.painted=x}}),setFilter:()=>{},getCenter:()=>[0,0],getZoom:()=>1,fitBounds:(b)=>{globalThis.camera={action:"fit",bounds:b}},jumpTo:(v)=>{globalThis.camera={action:"jump",...v}}};ready=Promise.resolve()');
 run('views.clear();lastPage="";globalThis.camera=null');
 await route(location.hash);
 assert.equal(run('camera.action'),'fit','Initial deep link fits the country instead of caching the startup world camera');
 assert(run('painted.features.some(f=>f.properties.country==="BRA"&&Number.isFinite(f.properties.value))'),'Country focus retains Brazilian weather');
 assert(run('painted.features.some(f=>f.properties.country==="USA"&&Number.isFinite(f.properties.value))'),'Country focus retains US weather');
 assert.equal(run('painted.features.find(f=>f.id===state.unit).properties.value'),response);
 assert.equal(run('painted.features.find(f=>f.id===state.unit).properties.color'),color);
 assert.equal(run('painted.features.length'),run('new Set(painted.features.map(f=>f.id)).size'));
 await route(base+'&metric=enso&index=mei&model=quadratic&mode=advanced');assert.equal(run('detailData.record.response.value'),response);assert.equal(run('C.color(detailData.record.value,scale)'),color);
 await route(base+'&layer=precipitation&statistic=p95&metric=enso&exposure=event&peak=3');assert(Number.isFinite(run('detailData.record.response.x')));
 assert(document.querySelector('#detail').textContent.includes('its peak is not the crop-window mean'));
 const baseline=run('detailData.obs.reduce((a,r)=>a+r[1],0)/detailData.obs.length'),native=run('C.estimate(detailData.record.fit,state.model,detailData.record.response.x).value');
 assert(Math.abs(run('detailData.record.response.value')-100*native/baseline)<1e-5,'Percent response independently agrees with the observed data average');
 assert.equal(run('C.unit(state)'),'%');
 assert(document.querySelector('.result').textContent.includes('95th-percentile average'));
 assert(document.querySelector('#legend-title').textContent.includes('% of regional average'));
 assert(document.querySelector('.chart-box').textContent.includes('mm/day'),'Observed time series remain native');

 run('download=(name,rows)=>{globalThis.savedRows=rows}');document.querySelector('#download-unit').onclick();
 assert(run('savedRows[0].includes("valid_precip_days")'));assert(run('savedRows[0].includes("rainfall_total_mm")'));assert.equal(run('savedRows[1].length'),run('savedRows[0].length'));
 assert.equal(run('savedRows[1][savedRows[0].indexOf("units")]'),'mm/day');
 assert.equal(run('savedRows[1][savedRows[0].indexOf("estimate_units")]'),'%');
 assert.equal(run('savedRows[1][savedRows[0].indexOf("baseline_statistic")]'),'p95');
 assert.equal(run('savedRows[1][savedRows[0].indexOf("native_estimate")]'),native);
 document.querySelector('#download-map').onclick();assert.equal(run('savedRows.find(r=>r[3]===state.unit)[9]'),run('detailData.record.value'));
 assert.equal(run('savedRows[1].length'),run('savedRows[0].length'));
 const pctValue=run('detailData.record.value');
 await route(base+'&layer=precipitation&statistic=p95&metric=enso&exposure=event&peak=3&rainUnits=native');
 assert.equal(run('detailData.record.value'),native);assert.equal(run('C.unit(state)'),'mm/day');
 await route(base+'&layer=precipitation&statistic=p95&metric=enso&exposure=event&peak=3&mode=advanced');
 assert.equal(run('detailData.record.value'),pctValue,'Simple/Advanced retains the same percentage result');
 await route(base+'&layer=precipitation&metric=trend');
 assert.equal(run('C.unit(state)'),'% per decade');
 assert.equal(run('scale.hi'),10,'Wheat rainfall trend uses a compact ±10% per decade scale');
 assert(document.querySelector('#legend-ticks').textContent.includes('≤ -10'));
 assert(document.querySelector('#legend-ticks').textContent.includes('≥ 10'));
 assert(document.querySelector('#color-range-note').textContent.includes('retain exact values'));
 assert(run('selected.some(r=>r.enough&&r.value>scale.hi)'),'Extreme estimates remain available above the color limit');
 assert(Math.abs(run('detailData.record.trend.value-detailData.record.trend.native.value*100/detailData.record.stats.mean'))<1e-12);

 await route(base+'&metric=trend');assert(document.querySelector('.result').textContent.includes('per decade'));
 await route(base+'&layer=yield&metric=enso');assert(run('detailData.record.response'));assert(document.querySelector('#detail').textContent.includes('log spacing'));
 await route('#/?crop=wheat&layer=precipitation&metric=enso');
 const globalColors=run('JSON.stringify(painted.features.map(f=>[f.id,f.properties.color]))');
 await route('#/country/IND?crop=wheat&layer=precipitation&metric=enso');
 assert.equal(run('JSON.stringify(painted.features.map(f=>[f.id,f.properties.color]))'),globalColors,'World and country views retain identical global coverage and colors');
 const countryCamera=run('JSON.stringify(camera)');
 await route(base+'&layer=precipitation&metric=enso');
 assert.equal(run('JSON.stringify(camera)'),countryCamera,'Opening a regional panel retains the country camera');
 await route('#/country/IND?crop=wheat&layer=precipitation&metric=enso');
 assert.equal(run('JSON.stringify(camera)'),countryCamera,'Closing a regional panel retains the country camera');
 document.querySelector('#world-map').onclick();await run('render()');
 assert.equal(run('state.kind'),'world');assert.equal(run('camera.bounds[0][0]'),-175,'Show whole world resets the view');
 await route('#/country/AFG?crop=wheat');assert(run('selected.filter(r=>r.country==="AFG").every(r=>!r.enough)'),'Missing national weather stays missing');
 await route('#/country/AFG?crop=wheat&layer=yield');assert(run('selected.some(r=>r.country==="AFG"&&r.enough)'),'Yield remains usable without weather');
 assert(run('painted.features.some(f=>f.id==="AFG"&&Number.isFinite(f.properties.value))'),'National yield fallback is drawn');
 await route('#/country/IND?crop=wheat&resolution=national');assert(run('selected.filter(r=>r.country==="IND").every(r=>!r.enough)'));
 assert(!document.querySelector('#status').classList.contains('error'));
 console.log('PASS climate linked charts, common years, native and percent weather/MEI/event fits, global coverage, country cameras, mode preservation, trends, downloads and missing national weather without loss of yields');
})().catch(e=>{console.error(e);process.exitCode=1});
