const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {parseHTML}=require('linkedom');
const ROOT=path.join(__dirname,'../global');
const {window}=parseHTML(fs.readFileSync(path.join(ROOT,'archive.html'),'utf8')),document=window.document;
let scrollResets=0;window.scrollTo=()=>{scrollResets++;};
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._value??(this.querySelector('option[selected]')||this.querySelector('option'))?.value??''},set(v){this._value=String(v)},configurable:true});
const location={hash:'',href:'https://example.org/global/'};const requests=[];
const context=vm.createContext({document,window,location,history:{replaceState(a,b,hash){location.hash=hash}},navigator:{clipboard:{writeText:async()=>{}}},maplibregl:{Map:function(){throw Error('Test accessible no-WebGL mode')}},URL,URLSearchParams,Blob,setTimeout,console,fetch:async p=>{requests.push(p);return {ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'))}}});
context.AtlasModel=require(path.join(ROOT,'model.js'));context.AtlasResponse=require(path.join(ROOT,'response.js'));const run=s=>vm.runInContext(s,context);
run(fs.readFileSync(path.join(ROOT,'app.js'),'utf8'));
(async()=>{
 for(let i=0;i<30&&!document.querySelector('#locations a');i++)await new Promise(r=>setTimeout(r,5));
 assert(document.querySelector('#locations a'));assert(!requests.some(r=>r.includes('/observations/')),'World must not load regional observations');
 console.log('World initial requests:',requests.length);
 async function route(hash){location.hash=hash;await run('render()');assert(!document.querySelector('#status').classList.contains('error'),document.querySelector('#status').textContent)}
 await route('#/country/JP?crop=wheat');assert(document.querySelector('#title').textContent==='Japan');assert(document.querySelectorAll('#locations a').length===47);assert.equal(document.querySelectorAll('#crop option').length,2);assert(!requests.some(r=>r.includes('/observations/')));
 await route('#/region/JP/JP.ADM1.00001?crop=wheat');assert(document.querySelectorAll('#detail circle').length===18);assert.equal(document.querySelectorAll('#detail tbody tr').length,18);
 assert.equal(run('detailSeries.periods.available.n'),18);
 assert(document.querySelector('.enso-axis-title').textContent.includes('°C'));
 assert(document.querySelectorAll('.enso-point').length>=18);
 assert(document.querySelector('.enso-note').textContent.includes('standard deviation'));
 assert(document.querySelector('#detail thead').textContent.includes('Niño 3.4'));
 run('download=(name,text)=>{globalThis.savedCsv=text}');document.querySelector('#download').onclick();
 assert(run('savedCsv').includes('"nino34_C"'));assert(run('savedCsv').includes('NOAA PSL ERSSTv6'));
 await route('#/region/JP/JP.ADM1.00001?crop=wheat&period=2015-2024');assert.equal(document.querySelectorAll('#detail tbody tr').length,run('detailSeries.periods[state.period].n'));
 await route('#/country/DE?crop=wheat');assert(document.querySelector('#subtitle').textContent.includes('not yet included'));assert.equal(document.querySelectorAll('#locations a').length,0);
 await route('#/region/IN/IN.ADM2.00001?crop=wheat&season=Summer');assert(!document.querySelector('#detail').hidden);
 const cat=JSON.parse(fs.readFileSync(path.join(ROOT,'data/2026-09-26/catalog.json')));
 let cases=0;
 for(const [c,data] of Object.entries(cat.countries))for(const [crop,seasons] of Object.entries(data.crops))for(const season of seasons){
   await route('#/country/'+c+'?'+new URLSearchParams({crop,season}));cases++;assert.equal(run('selected.every(r=>r.season===state.season)'),true);
 }
 await route('#/country/MY?crop=rice-paddy&basis=planted');assert(run('selected.every(r=>r.basis==="planted")'));
 await route('#/country/MY?crop=rice-paddy&basis=harvested');assert(run('selected.every(r=>r.basis==="harvested")'));
 await route('#/country/JP?crop=wheat&minimum=80&period=2015-2024');assert(run('selected.filter(r=>r.enough).every(r=>r.stats.completeness>=.8)'));
 await route('#/country/IN?crop=wheat');assert(run('selected.filter(r=>r.country==="IN").every(r=>r.season==="Rabi")'));
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&view=world');
 assert(document.querySelector('.enso-note').textContent.includes('Nov (previous year)–Apr'));
 const fullChart=document.querySelector('#detail svg').outerHTML;
 const climatePath='../enso/2026-09-26/nino34.json';
 run(`cache.set('${climatePath}',Promise.resolve(null))`);
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&period=2015-2024&view=world');
 assert(document.querySelectorAll('#detail circle').length>0);assert(document.querySelector('.enso-note').textContent.includes('unavailable'));
 run(`cache.delete('${climatePath}')`);
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&view=world');assert.equal(document.querySelector('#detail svg').outerHTML,fullChart);
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&metric=enso&model=quadratic&amplitude=3&view=world');
 assert(!document.querySelector('#enso-controls').hidden);assert.equal(document.querySelectorAll('.fit-observation').length,25);assert.equal(document.querySelectorAll('.scenario-point').length,1);assert(document.querySelector('.response-flag').textContent.includes('Outside observed'));
 assert(document.querySelector('.response-card').textContent.includes('95% pointwise'));assert(!document.querySelector('#detail').innerHTML.includes('NaN'));
 document.querySelector('#download-fit').onclick();assert(run('savedCsv').includes('trend_adjusted_log_yield'));assert.equal(run('savedCsv').trim().split('\r\n').length,26);
 document.querySelector('#download-responses').onclick();assert(run('savedCsv').includes('lo95_pct'));assert(run('savedCsv').includes('planted'));
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&metric=enso&model=hinge&exposure=event&peak=3&peakYear=2026&peakMonth=11&harvest=1&view=world');
 assert(!document.querySelector('#event-controls').hidden);assert(document.querySelector('#amplitude-control').hidden);assert.equal(document.querySelectorAll('.profile-box').length,1);assert(document.querySelector('.profile-box').textContent.includes('2027'));
 assert.equal(document.querySelectorAll('.fit-observation').length,25);assert(document.querySelector('.enso-axis-title'),'Raw observed chart must retain right-hand ENSO axis');
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&metric=enso&period=2015-2024');assert.equal(document.querySelectorAll('.fit-observation').length,0);assert(document.querySelector('.response-block').textContent.includes('Needs 20'));assert(document.querySelectorAll('.yield-series circle').length>0);assert(run('selected.every(r=>!r.enough)'));
 await route('#/region/JP/JP.ADM1.00001?crop=wheat&metric=enso');assert(document.querySelector('.response-block').textContent.includes('18 available'));assert(document.querySelectorAll('.yield-series circle').length===18);
 await route('#/country/IN?crop=wheat&metric=enso&amplitude=3&support=observed');assert(run('selected.filter(r=>r.enough).every(r=>!r.response.extrapolated)'));
 await route('#/country/IN?crop=wheat&metric=enso&evidence=validated');assert(run('selected.filter(r=>r.enough).every(r=>r.response.validated)'));
 await route('#/country/IN?crop=wheat&metric=enso&evidence=interval');assert(run('selected.filter(r=>r.enough).every(r=>r.response.interval)'));
 await route('#/?crop=rice&metric=yield');assert.equal(run('state.crop'),'rice');assert.equal(run('new Set(selected.filter(r=>r.enough).map(r=>r.country)).size'),9);
 assert.equal(document.querySelectorAll('#crop option').length,3);assert(document.querySelector('#legend-title').textContent.includes('Paddy-equivalent'));
 assert(run('selected.some(r=>r.source_crop==="rice-milled")&&selected.some(r=>r.source_crop==="rice-paddy")'));
 await route('#/region/IN/IN.ADM2.00232?crop=rice-milled&metric=enso&model=quadratic&amplitude=3&view=world');
 assert.equal(run('state.crop'),'rice');assert(location.hash.includes('crop=rice&'));assert(document.querySelector('.rice-note').textContent.includes('divided by 0.67'));
 assert.equal(run('detailSeries.source_crop'),'rice-milled');assert(document.querySelectorAll('.fit-observation').length>0);assert(document.querySelector('.enso-axis-title'));
 assert(document.querySelector('.source-note a[href$="IN-rice-milled.json"]'));
 document.querySelector('#download').onclick();const riceCsv=run('savedCsv');assert(riceCsv.includes('"original_yield_t_ha"'));assert(riceCsv.includes('"paddy_equivalent"'));assert(riceCsv.includes('"rice-milled"'));
 const csvRows=riceCsv.trim().split('\r\n').map(r=>r.slice(1,-1).split('","')),header=csvRows[0],row=csvRows[1];
 assert(Math.abs(+row[header.indexOf('yield_t_ha')]*.67-row[header.indexOf('original_yield_t_ha')])<1e-10);
 document.querySelector('#download-fit').onclick();assert(run('savedCsv').includes('"weight_conversion_factor"'));assert(run('savedCsv').includes('"original_yield_t_ha"'));
 document.querySelector('#download-responses').onclick();assert(run('savedCsv').includes('"source_crop"'));assert(run('savedCsv').includes('"rice-paddy"'));
 await route('#/region/KR/KR.ADM1.00001?crop=rice&metric=enso');assert.equal(run('detailSeries.source_crop'),'rice-paddy');assert.equal(run('detailSeries.conversion_factor'),1);assert(document.querySelector('.rice-note').textContent.includes('no weight conversion'));
 assert.equal(run('selected.filter(r=>r.country==="KR").length'),10);
 await route('#/country/MY?crop=rice&basis=harvested&period=2015-2024&metric=yield');assert(run('selected.every(r=>r.basis==="harvested")'));
 run("cache.set('../fits/2026-09-26/wheat.json',Promise.resolve(null))");
 await route('#/region/IN/IN.ADM2.00267?crop=wheat&metric=enso');assert(document.querySelector('#status').textContent.includes('could not be loaded'));assert(document.querySelectorAll('.yield-series circle').length===25);
 assert(scrollResets>5,'New location pages reset the scroll position');
 console.log('PASS: '+cases+' country/crop/season routes, region chart and table, fixed periods, missing countries, separate denominators, coverage screen, lazy observation loads, page scroll resets.');
})().catch(e=>{console.error(e);process.exitCode=1});
