const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),zlib=require('zlib');
const {parseHTML}=require('linkedom');
const ROOT=path.join(__dirname,'../global'),M=require(path.join(ROOT,'merged-model.js'));
const base=path.join(ROOT,'data',M.BASE_RELEASE),read=f=>JSON.parse(f.endsWith('.gz')?zlib.gunzipSync(fs.readFileSync(path.join(base,f))):fs.readFileSync(path.join(base,f),'utf8'));
const {window}=parseHTML(fs.readFileSync(path.join(ROOT,'index.html'),'utf8')),document=window.document;
window.scrollTo=()=>{};window.innerWidth=1200;window.innerHeight=800;
window.HTMLElement.prototype.getBoundingClientRect=()=>({top:120,bottom:500});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._value??(this.querySelector('option[selected]')||this.querySelector('option'))?.value??''},set(v){this._value=String(v)},configurable:true});
Object.defineProperty(window.HTMLSelectElement.prototype,'selectedOptions',{get(){return [...this.querySelectorAll('option')].filter(o=>o.value===this.value)},configurable:true});
const location={hash:'#/country/IND?crop=wheat',href:'https://example.org/global/'},requests=[];let interrupted=false;
const context=vm.createContext({document,window,location,history:{replaceState(a,b,hash){location.hash=hash},pushState(a,b,hash){location.hash=hash}},navigator:{clipboard:{writeText:async()=>{}}},maplibregl:{Map:function(){throw Error('Test no-WebGL accessibility')}},URL,URLSearchParams,Blob,Response,DecompressionStream,setTimeout,console,fetch:async p=>{requests.push(p);if(!interrupted&&p.endsWith('geometry/IND.json.gz')){interrupted=true;throw new TypeError('Simulated interrupted connection');}try{return new Response(fs.readFileSync(path.join(ROOT,p)),{status:200})}catch{return new Response('',{status:404})}}});
context.AtlasReliability=require(path.join(ROOT,'merged-reliability.js'));context.AtlasModel=M;context.AtlasResponse=require(path.join(ROOT,'merged-response.js'));const run=s=>vm.runInContext(s,context);
run(fs.readFileSync(path.join(ROOT,'merged-app.js'),'utf8'));
(async()=>{
 for(let i=0;i<300&&!document.querySelector('#locations a');i++)await new Promise(r=>setTimeout(r,50));
 assert(document.querySelector('#locations a'),document.querySelector('#status').textContent);
 const route=async hash=>{location.hash=hash;await run('render()');assert(!document.querySelector('#status').classList.contains('error'),document.querySelector('#status').textContent)};
 assert(!requests.some(p=>p.includes('/observations/')));
 await route('#/country/IN?crop=wheat');assert.equal(run('state.country'),'IND');
 const wheat=read('wheat.json.gz');
 let picked=M.select(wheat,M.parse('#/?crop=wheat'));
 assert(new Set(picked.filter(r=>r.enough).map(r=>r.country)).size>100);
 assert(new Set(picked.filter(r=>r.enough&&r.level!=='ADM0').map(r=>r.country)).size>35);
 for(const cc of new Set(picked.map(r=>r.country)))assert(new Set(picked.filter(r=>r.country===cc).map(r=>r.tier)).size===1,'One source tier per country');
 assert(picked.filter(r=>r.country==='IND').every(r=>r.source==='hvstat'));
 assert(picked.filter(r=>r.country==='USA').every(r=>r.source==='gmfd'));
 const IN=picked.find(r=>r.country==='IND'&&r.periods['1981-2024'].n>=20);assert(IN);
 await route('#/region/IND/'+encodeURIComponent(IN.id)+'?crop=wheat&metric=enso&index=mei');
 assert(document.querySelector('.enso-axis-title').textContent.includes('index units'));
 assert(document.querySelector('#detail').textContent.includes('two-month'));
 assert(document.querySelectorAll('.fit-observation').length>=20,document.querySelector('#detail').textContent.slice(0,1000));
 assert(!document.querySelector('#detail').textContent.includes('undefined'));
 assert(!document.querySelector('#detail').innerHTML.includes('NaN'));
 run('download=(name,text)=>{globalThis.savedCsv=text}');document.querySelector('#download').onclick();
 assert(run('savedCsv').includes('upstream_primary'));assert(run('savedCsv').includes('index_version'));
 document.querySelector('#download-fit').onclick();assert(run('savedCsv').includes('"mei"'));
 await route('#/region/IND/'+encodeURIComponent(IN.id)+'?crop=wheat&metric=enso&model=quadratic&exposure=event&peak=3&harvest=1');
 assert(document.querySelector('.profile-box'));assert(document.querySelectorAll('.scenario-point').length===1);
 const native=run('selected.find(r=>r.id===state.unit).response.x');assert(Number.isFinite(native));
 await route('#/region/IND/'+encodeURIComponent(IN.id)+'?crop=wheat&metric=enso&index=mei&exposure=event');assert.equal(run('state.exposure'),'season');assert(document.querySelector('#event-preset').hidden);
 await route('#/region/IND/'+encodeURIComponent(IN.id)+'?crop=wheat&metric=enso&scale=sd&amplitude=1');
 assert.equal(run('selected.find(r=>r.id===state.unit).response.x'),run('selected.find(r=>r.id===state.unit).fit.x_sd'));
 await route('#/region/IND/'+encodeURIComponent(IN.id)+'?crop=wheat&metric=trend');assert(document.querySelector('.response-card').textContent.includes('per decade'));
 await route('#/country/USA?crop=wheat&resolution=national');assert.equal(document.querySelectorAll('#locations a').length,1);assert(run('selected.filter(r=>r.country==="USA").every(r=>r.level==="ADM0")'));
 await route('#/country/USA?crop=wheat&season='+encodeURIComponent('main · Spring wheat'));assert(run('selected.filter(r=>r.country==="USA").every(r=>r.source_crop==="wheat_spring")'));
 const rice=read('rice.json.gz');const unknown=rice.find(r=>!r.comparable&&r.periods.available.n);assert(unknown);
 assert(!M.select([unknown],M.parse('#/?crop=rice')).some(r=>r.enough));assert(M.select([unknown],M.parse('#/?crop=rice&metric=enso')).some(r=>r.enough));
 const nr=M.select(rice,M.parse('#/?crop=rice')).find(r=>r.country==='IND');assert(nr);
 await route('#/region/IND/'+encodeURIComponent(nr.id)+'?crop=rice');assert(document.querySelector('.rice-note').textContent.includes('milled'));
 await route('#/country/AFG?crop=wheat');assert(run('selected.filter(r=>r.country==="AFG").every(r=>r.level==="ADM0")'));
 assert(document.querySelectorAll('#locations a').length===1);
 const beforeWorld=requests.length;
 await route('#/?crop=wheat');
 assert.equal(run('shapes.features.find(f=>f.id==="AFG").properties.id'),'AFG');
 assert.equal(run('shapes.features.find(f=>f.id==="AFG").properties.tier'),3);
 assert(!requests.slice(beforeWorld).some(p=>p.endsWith('geometry/AFG.json.gz')));
 assert.equal(run('shapes.features.length'),run('new Set(shapes.features.map(f=>f.id)).size'));
 // The full UI loads the matching country check shard and exports its metadata.
 await route('#/country/USA?crop=wheat&metric=enso&estimator=pooled');
 const poolUnit=run('selected.find(r=>r.country==="USA"&&r.fit?.models.linear?.coef).id');
 await route('#/region/USA/'+encodeURIComponent(poolUnit)+'?crop=wheat&metric=enso&estimator=pooled');
 assert(document.querySelector('.pool-comparison').textContent.includes('Matched holdout skill'));
 assert(document.querySelector('.reliability').textContent.includes('including this unit'));
 assert(!document.querySelector('#detail').innerHTML.includes('undefined'));
 document.querySelector('#download-checks').onclick();
 const checkDownload=JSON.parse(run('savedCsv'));
 assert.equal(checkDownload.selection.estimator,'pooled');assert(checkDownload.checks.group_units>=3);
 assert(checkDownload.checks.models.linear.comparison.individual.every(Number.isFinite));
 document.querySelector('#download-responses').onclick();assert(run('savedCsv').includes('field_q_BY'));assert(run('savedCsv').includes('pool_group'));
 await route('#/region/USA/'+encodeURIComponent(poolUnit)+'?crop=wheat&metric=enso&estimator=pooled&index=mei');
 assert(document.querySelector('#detail').textContent.includes('Pooling available for 1981–2024'));
 assert(document.querySelector('#estimator [value="pooled"]').disabled);
 assert(!document.querySelector('.fit-curve'),'Unavailable pooling must not silently show an individual curve');
 assert(interrupted&&requests.filter(p=>p.endsWith('geometry/IND.json.gz')).length===2);
 const cassava=read('cassava.json.gz'),quarantined=cassava.find(r=>r.country==='BRA'&&!r.mapped&&!r.periods.available.n);assert(quarantined);
 assert.equal(M.select([quarantined],M.parse('#/?crop=cassava')).length,1,'Excluded-only series remain discoverable');
 await route('#/region/BRA/'+encodeURIComponent(quarantined.id)+'?crop=cassava&source=gmfd');
 assert(document.querySelector('#detail').textContent.includes('Boundary unavailable'));
 assert(document.querySelector('#detail').textContent.includes('Original source rows'));
 console.log('PASS merged priority, national fallback, spring/winter wheat, source QC download, MEI alignment labels, SD and event scenarios, trend, rice, lazy observations.');
})().catch(e=>{console.error(e);process.exitCode=1});
