"""Write a dated, printable bulletin and reporter walkthrough from the frozen release."""
import json
from html import escape
from pathlib import Path
from urllib.parse import urlencode

ROOT=Path(__file__).resolve().parents[1]; SITE=ROOT/'site'; RELEASE='2026-10-08'
panels={p['key']:p for p in json.loads((SITE/'data'/RELEASE/'panels.json').read_text())}
display=json.loads((SITE/'display'/RELEASE/'summary.json').read_text())
world=json.loads((SITE/'data'/RELEASE/'world.json').read_text())
def pct(v):return 'Unavailable' if v is None else f'{v:+.1f}%'
def prediction(p,sc='medium'):return next(x for x in p['predictions'] if x['method']=='index_outlook' and x['scenario']==sc)
def link(key,view='season'):
    iso,crop,season=key.split('|');return './#/'+view+'/'+iso+'?'+urlencode(dict(crop=crop,season=season,release=RELEASE))
style='''body{font:16px/1.55 Georgia,serif;color:#203329;background:#f5f5ef;margin:0}main{max-width:850px;background:white;margin:30px auto;padding:42px}h1{font:34px/1.1 Helvetica,sans-serif}h2{font:20px Helvetica,sans-serif;margin-top:28px}h3{font:16px Helvetica,sans-serif}a{color:#176957}table{border-collapse:collapse;width:100%;font:12px/1.4 Helvetica,sans-serif}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}small,.note{font:12px/1.5 Helvetica,sans-serif;color:#536058}.kicker{font:12px Helvetica,sans-serif;letter-spacing:1px}button{padding:8px;background:white;border:1px solid #87968b;border-radius:4px}.tools{font:14px Helvetica,sans-serif}.table-wrap{overflow:auto}@media(max-width:700px){main{padding:20px;margin:0}h1{font-size:28px}}@page{size:letter;margin:18mm}@media print{body{background:white;font-size:11pt}main{padding:0;margin:0;max-width:none}.page{break-after:page}.appendix{break-before:page}.tools{display:none}h1{font-size:26px}table{font-size:9pt}h2{font-size:16px;margin-top:18px}}'''
def html(title,body):return f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><style>{style}</style><main><p class="tools"><a href="./#/season?release={RELEASE}">Open the atlas</a> · <a href="bulletin-{RELEASE}.pdf">Download bulletin PDF</a> · <button onclick="window.print()">Print this page</button></p>{body}</main></html>'
keys=['USA|maize|main','IND|rice_milled|Kharif','BRA|maize|main','ARG|maize|main']
rows=[]
for key in keys:
    p=panels[key];m=prediction(p);w=p['weather']
    rows.append(f'<tr><td><a href="{link(key)}">{escape(p["label"])}</a><br>{p["harvest_year"]}; {escape(p["status"])}</td><td>{pct(prediction(p,"low")["pct"])}</td><td>{pct(m["pct"])}</td><td>{pct(prediction(p,"high")["pct"])}</td><td>{pct(m["lo"])} to {pct(m["hi"])}</td><td>{pct(w["pct_panel"]) if w else "Unavailable"}<br>{"Meets checks" if w and w["usable_panel"] else "Checks not met" if w else "Not scored"}</td></tr>')
month=9;years=[2026,2023,2015,1997,1982]
history=[next(x for x in display['monthly'] if x['year']==y and x['month']==month) for y in years]
hrows=''.join(f'<tr><td>{r["year"]}</td><td>{r["nino34"]:+.2f} °C</td><td>{r["nino34_rel"]:+.2f} °C</td></tr>' for r in history)
us=panels[keys[0]];india=panels[keys[1]];brazil=panels[keys[2]];arg=panels[keys[3]]
body=f'''<section class="page"><p class="kicker">EL NIÑO CROP WATCH · RELEASE {RELEASE}</p><h1>ENSO and the 2026–27 harvests</h1><p class="note">Observations through September 30, 2026. ENSO scenarios from the September 2026 outlook. This bulletin summarizes the frozen atlas release; it does not incorporate a later forecast issue.</p>
<p>We find different crop responses across countries and substantial uncertainty within each country. The central ENSO scenario implies a yield increase for US and Argentine maize and a decrease for Indian Kharif rice and Brazilian maize in the selected panels. Observed weather can point in another direction: the US weather estimate is {pct(us['weather']['pct_panel'])}, while the ENSO scenario is {pct(prediction(us)['pct'])}. The methods cover different sets of reporting units.</p>
<h2>ENSO tracking at the same point in earlier events</h2><p>The September 2026 monthly Niño 3.4 anomaly is {history[0]['nino34']:.2f} °C. Removing the tropical mean anomaly gives a relative Niño 3.4 value of {history[0]['nino34_rel']:.2f} °C. We compare September with September in earlier events using the same index definitions. These monthly values do not determine the coming winter’s peak.</p><table><thead><tr><th>September</th><th>Niño 3.4</th><th>Relative Niño 3.4</th></tr></thead><tbody>{hrows}</tbody></table>
<p>The stored outlook uses lower, central and higher winter ENSO paths. Their relative-index DJF means are {world['index']['scenario_rel_djf']['low']:.2f}, {world['index']['scenario_rel_djf']['medium']:.2f} and {world['index']['scenario_rel_djf']['high']:.2f} °C. We apply those paths to each crop’s growing season, so timing matters alongside event strength.</p>
<h2>Conditional yield changes relative to trend</h2><div class="table-wrap"><table><thead><tr><th>Crop and harvest</th><th>Lower ENSO</th><th>Central</th><th>Higher ENSO</th><th>Central coefficient bounds</th><th>Weather so far</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p class="note">Negative values denote losses relative to the fitted yield trend. Lower and higher refer to ENSO strength, not loss percentiles. Bounds average local 95% coefficient limits. They are not calibrated national 95% intervals; other harvest drivers add uncertainty.</p></section>
<section class="page"><h2>Implications for monitoring</h2><p>We would follow the US maize weather estimate alongside local crop reports because the weather estimate meets the release’s seasonal coverage and historical-skill checks. The positive ENSO scenario is a historical conditional relationship. The negative weather estimate reflects the conditions observed so far. Neither number establishes the final yield outcome.</p><p>Indian Kharif rice has a negative central ENSO estimate and a negative weather estimate, but the scenario interval includes gains. The district maps show geographic differences that the national average obscures. Stable merged HarvestStat districts preserve comparability through boundary changes.</p><p>The Brazilian maize weather estimate has only {100*brazil['weather']['coverage_share']:.2f}% production coverage and fails the historical-skill check. We would not treat its large negative number as an actionable national outlook. The Argentine maize panel is not yet planted; its conditional ENSO estimate provides a scenario to track as weather observations accumulate.</p>
<h2>From harvest risk to food security</h2><p>Local yield departures can affect farm incomes, procurement and regional trade even when gains elsewhere offset losses in broader totals. Stocks, prices, trade restrictions, incomes and conflict also affect food access. The atlas does not translate a yield estimate into a population needing assistance.</p><p><a href="https://fews.net/global/special-report/october-2026">FEWS NET’s October 6 report</a> identifies particular concern in Southern Africa and East African areas with one main rainy season. FEWS NET also distinguishes rainfall and harvest impacts from later lean-season food-security effects. We would use that regional assessment to interpret the atlas’s crop-specific estimates and calendars.</p>
<h2>How to use the release</h2><p>Choose a crop on the atlas landing page and open a named country and season. Read the uncertainty and reliability checks beside the estimate, then inspect local coverage. The weather view places observed rainfall and temperature beside their historical ENSO expectations. Yield history places the crop’s ENSO exposure beside observed yields and trend departures.</p><p>Copy a link to preserve the release and selection. Download a table or figure with its provenance. For a country briefing, open the relevant season and use “Print / save country brief.” Changes since the preceding build are listed on the landing page; changes in methods and coverage can move an estimate without new weather observations.</p><p class="note">Citation: ENSO yield atlas, release {RELEASE}. Sources and downloadable numerical results: <a href="./#/about?release={RELEASE}">atlas methods and data</a>. Prepared for review and discussion using the frozen September observation cutoff.</p></section>
<section class="appendix"><h2>Appendix: data and methods</h2><p>We prioritize HarvestStat v0.1 and v0.2, then Hultgren replication data with agency extensions, then FAOSTAT national records. India uses merged HarvestStat districts. Detailed Hultgren crop calendars, FAO/GIEWS and RiceAtlas provide growing windows where available; each unit page identifies the actual source. We preserve source crop types and keep overlapping seasonal and Annual panels separate.</p><p>We fit long-term yield trends and estimate yield relationships with standard and relative Niño 3.4. The analysis selects a unit’s own fit where its record is sufficiently long, with regional or country fallbacks for short records. Country and regional regressions are separate estimates, so they need not match an average of the local map. We retain those differences and show the estimator level.</p><p>ENSO scenarios combine the observed index with lower, central and higher outlook paths. We apply the paths over each crop’s growing window and weight the conditional changes using the analysis release’s production weights. HarvestStat production shares and Hultgren cropped-area shares allocate FAOSTAT national totals; area-based allocations are proxies for local production. Temperature and rainfall summaries use BEST and CHIRPS. The weather regression uses observations from the elapsed part of each window. Historical tests use rolling origins and exclude the target harvest year and its neighbors from training.</p><p>Weather checks require enough of the growing season, sufficient production coverage, bounded estimation error and positive historical skill at the current lead. Missing skill and negative skill have different meanings. The index-outlook check assumes the future index is known; it does not establish operational forecast skill. A matched-footprint comparison uses identical production weights for both sets of unit estimates and appears separately from the fitted country weather estimate. We do not assign a new aggregate confidence interval to that descriptive comparison.</p><p>We shade historical yields using ENSO exposure matched to the exact series and harvest year, including crops spanning calendar years. We retain QC flags, duplicate source observations and missing years for inspection. Full source hashes, methods, build revisions and numerical validation are available with the downloadable release.</p></section>'''
(SITE/f'bulletin-{RELEASE}.html').write_text(html('ENSO crop bulletin · '+RELEASE,body))
body=f'''<p class="kicker">REPORTER WALKTHROUGH · RELEASE {RELEASE}</p><h1>Reading the El Niño Crop Watch</h1><p>We compare historical crop responses, observed seasonal weather and conditional yield changes. A useful story identifies the crop, place, harvest year, growing season and observation cutoff. We describe conditional yield changes relative to trend; a statement about global food supply or household food access requires additional evidence.</p>
<h2>A historical relationship with evidence</h2><p>Open <a href="{link('ARG|maize|main','response')}">Argentine maize relationships</a>. The country regression gives {pct(arg['response']['pct_per_degC'])} per +1 °C of relative Niño 3.4, with an interval of {pct(arg['response']['lo'])} to {pct(arg['response']['hi'])}. The relationship survives the release’s multiple-comparison adjustment (q={arg['response']['q']:.3f}). Then inspect the local map and regional estimates. A positive historical relationship is not evidence that every district benefits or that the coming harvest gain is known.</p>
<h2>When observed weather differs from ENSO expectations</h2><p>Open <a href="{link('USA|maize|main')}">US maize this season</a>. Compare the ENSO and weather cards, then open the comparison over the same places. The matched unit means are {pct(display['common']['USA|maize|main']['index_pct'])} for ENSO and {pct(display['common']['USA|maize|main']['weather_pct'])} for weather. Check the skill chart at the current lead and compare observed temperature and rainfall with their ENSO expectations. Describe the geographic coverage whenever citing either estimate.</p>
<h2>When the evidence is insufficient</h2><p>Open <a href="{link('BRA|maize|main')}">Brazilian maize this season</a>. Most of the selected crop has not yet been planted. Weather coverage is {100*brazil['weather']['coverage_share']:.2f}% of production, and the weather method performs worse than trend in the corresponding historical test. The page preserves the number for inspection and labels the failed checks. A headline national loss based on that weather number would overstate the available evidence.</p>
<h2>A 25-minute walkthrough with discussion</h2><p>Spend five minutes explaining the three views and observation cutoff, five minutes on each example above, and five minutes on questions and exports. Peter and Klara could divide the examples between historical ENSO relationships and this season’s interpretation, subject to their availability. This page supplies an agenda and demonstration links; no webinar has been scheduled.</p>
<h2>Questions to ask before quoting a result</h2><p>Identify the baseline, sign and unit. Check whether the interval includes zero, whether a model passed its historical tests at this lead, and whether it is being applied beyond the fitted range. Confirm whether a national figure covers the whole country, a subset of reporting units or one season. Distinguish lower and higher ENSO scenarios from lower and higher loss percentiles.</p><p>Use the <a href="bulletin-{RELEASE}.html">dated release bulletin</a> for a short overview and <a href="./#/about?release={RELEASE}">methods and downloads</a> for provenance. The <a href="https://fews.net/global/special-report/october-2026">FEWS NET regional assessment</a> provides complementary food-security context. Any public article should retain the observation date and uncertainty next to the quoted estimate.</p>'''
(SITE/'reporters.html').write_text(html('Crop Watch · reporter walkthrough',body))
print('Built bulletin and reporter walkthrough from',RELEASE)
